# ==========================================
# GLOBALE STANDARDS (Gilt für alle Modelle)
# ==========================================
[*]
host = 0.0.0.0

flash-attn = true
load-mode = mmap+mlock
lazy-mode = off
parallel = 1
threads = 8
cont-batching = true

# Wichtig für Cline: Continuous Batching & Context Shift ohne Unified-Pool-Overhead
# OPTIMIERT: Entfernt, da MTP-Modelle kein Shifting unterstützen
# context-shift = true

# OPTIMIERT: Spart Overhead bei Single-User/Single-Slot
kv-unified = true          
parallel = 1



# OPTIMIERT FÜR VRAM-EINSPARUNG BEIM PREFILL
batch-size = 4096            # Reduziert von 4096 (senkt den logischen Overhead)
ubatch-size = 512            # Reduziert von 1024 -> Das spart ~1 GB Spitzen-VRAM!

jinja = true
reasoning-format = deepseek
reasoning-effort = xhigh
reasoning-preserve = on
cache-prompt = true


# ==========================================
# EINZELNE MODELLE (Der Name in [] ist die API-ID)
# ==========================================

; [Qwen3.8-27B-UD-Q5_K_XL]
; model = /devops/LocalAI/models/Qwen3.8-27B-UD-Q5_K_XL.gguf
; ctx-size = 65000
; spec-type = draft-mtp
; spec-draft-n-max = 3 
; spec-draft-p-min = 0.75
; gpu-layers = 99
; cache-type-k = q8_0
; cache-type-v = q8_0



; [Qwen3.8-27B-UD-Q5_K_M]
; model = /devops/LocalAI/models/Qwen3.8-27B-UD-Q5_K_M.gguf
; ctx-size = 65000
; spec-type = draft-mtp
; spec-draft-n-max = 3 
; spec-draft-p-min = 0.75
; gpu-layers = 99
; cache-type-k = q8_0
; cache-type-v = q8_0


[Qwen3.8-27B-UD-Q5_K_S]
model = /devops/LocalAI/models/Qwen3.8-27B-UD-Q5_K_S.gguf
ctx-size = 90000
spec-type = draft-mtp
spec-draft-n-max = 4 
spec-draft-p-min = 0.75
gpu-layers = 99
batch-size = 2048
ubatch-size = 512
cache-type-k = q8_0
cache-type-v = q4_0


[Qwen3.8-27B-UD-Q4_K_XL]
model = /devops/LocalAI/models/Qwen3.8-27B-UD-Q4_K_XL.gguf
ctx-size = 80000
spec-type = draft-mtp
spec-draft-n-max = 3 
spec-draft-p-min = 0.75
gpu-layers = 99
batch-size = 4096
ubatch-size = 2048
cache-type-k = q8_0
cache-type-v = q8_0


[Qwen3.6-35B-A3B-UD-Q4_K_XL]
model = /devops/LocalAI/models/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf
ctx-size = 14000
gpu-layers = 99
batch-size = 2048
ubatch-size = 128
cache-type-k = q8_0
cache-type-v = q4_0

; --- MTP (Multi-Token Prediction) Configuration ---
; "draft-mtp" tells the server to look for the internal MTP draft layers in the Unsloth GGUF file
spec-type = draft-mtp
; Generates 2 tokens ahead simultaneously. (Sweet spot for speed/VRAM overhead)
spec-draft-n-max = 3
; Standard temperature pruning for speculative drafting
spec-draft-p-min = 0.75


[Qwen3.6-35B-A3B-UD-IQ4_NL]
model = /devops/LocalAI/models/Qwen3.6-35B-A3B-UD-IQ4_NL.gguf
ctx-size = 131072
gpu-layers = 99
batch-size = 4096
ubatch-size = 1024
cache-type-k = q8_0
cache-type-v = q8_0

; --- MTP (Multi-Token Prediction) Configuration ---
spec-type = draft-mtp
spec-draft-n-max = 4
spec-draft-p-min = 0.75




